import React from "react";
import FixedIcon from "../../Components/FixedIcon/FixedIcon";
import Footer from "../../Components/Footer/Footer";
import Header from "../../Components/Header/Header";
import ResponseHeader from "../../Components/ResponseHeader/ResponseHeader";
import { Helmet } from "react-helmet";

const Premiere = () => {
  return (
    <main>
      <Helmet>
        <title>نهال آی تی | نمونه کار پریمیر</title>
      </Helmet>
      <header>
        <div className="max-lg:hidden">
          <Header />
        </div>
        <div className="lg:hidden">
          <ResponseHeader />
        </div>
      </header>
      <div className="bg-[#f5f5f9] pt-10 pb-10">
        <div className="container mx-auto">
          <h2 className="font-[shabnamBold] max-lg:text-3xl max-md:text-2xl max-sm:text-lg whitespace-nowrap tracking-tighter pt-8 mt-1  text-2xl sm:text-4xl text-center text-green-137 px-0 pb-10 sm:px-12">نمونه کارهای پریمیر</h2>
          <div className="flex items-center justify-center flex-wrap gap-5 mt-5">
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/n9Jrz/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/ZP5n3/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/5lPYT/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/P8Vb1/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/auIxr/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/XEtKL/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/lzSeh/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/cCwLS/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/xw0Hr/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/XdJo5/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/0TIrh/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/ZMdOT/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/2xv1P/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/edNvh/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/mlBMa/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/6xpza/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/dU54q/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/PfZ1r/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/UB4DG/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/M73h4/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/IQ95a/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/Nlreq/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/nKA90/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/qL0v1/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/zJd8w/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/ydC1U/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/nqKAa/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/yngYm/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/6fMNe/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/Ak9IE/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/V6281/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/pO5f0/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/LuPQw/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
            <div>
              <iframe
                title="movie"
                src="https://www.aparat.com/video/video/embed/videohash/UAYtL/vt/frame?titleShow=true"
                allowFullScreen={true}
                webkitallowfullscreen={true}
                mozallowfullscreen={true}
              ></iframe>
            </div>
          </div>
        </div>
      </div>
      <div>
        <FixedIcon />
      </div>
      <footer>
        <Footer />
      </footer>
    </main>
  );
};

export default Premiere;
